/**
 * Config-suggest orchestrator.
 *
 * Single public function `suggestConfig(...)`:
 *   1. Schema lookup (404 if unknown configType).
 *   2. Idempotency check (30s window): return prior batch with isDuplicate.
 *   3. Cap-guard claim.
 *   4. Filter aiSuggestable fields + mask context.
 *   5. Build prompt + 12s AbortController LLM call.
 *   6. Strict-parse + per-field schema validate.
 *   7. Persist N ConfigSuggestion docs with cost = batchCost / N (equal division).
 *   8. Audit log `ai_config_suggested`.
 *
 * Spec: `.sdd/specs/002-ai-assisted-config/spec.md`.
 */

import mongoose from 'mongoose';
import { randomUUID } from 'crypto';

import { AppError } from '../../../middleware/errorHandler';
import { createAuditLog } from '../../../shared/audit';
import { maskPII } from '../../../shared/llm/pii';
import { ConfigSuggestion } from '../../../models/platform/ConfigSuggestion';
import { createLLMClient, type LLMMessage } from '../../juvi/finance-agent/llm-client';
import { getRegisteredSchema } from '../config-registry';

import { tryClaimConfigSuggestSlot } from './cap-guard';
import { buildConfigSuggestPrompt, PROMPT_VERSION } from './prompt';
import { parseConfigSuggestions } from './parser';

const LLM_TIMEOUT_MS = 12_000;
const IDEMPOTENCY_WINDOW_MS = 30_000;

export interface SuggestionView {
  field: string;
  suggestedValue: unknown;
  confidence: number;
  rationale: string;
}

export interface SuggestConfigOptions {
  collegeProfile?: Record<string, unknown>;
  currentValues?: Record<string, unknown>;
  now?: Date;
}

export interface SuggestConfigResult {
  batchId: string;
  suggestions: SuggestionView[];
  llmModel: string;
  costInr: number;
  generatedAt: Date;
  capReached?: boolean;
  llmFallback?: boolean;
  isDuplicate?: boolean;
  reason?: string;
}

function nowOr(d?: Date): Date {
  return d ?? new Date();
}

async function callLLM(
  messages: LLMMessage[],
): Promise<{ text: string; costInr: number; model: string } | null> {
  const ctrl = new AbortController();
  const timer = setTimeout(() => ctrl.abort(), LLM_TIMEOUT_MS);
  try {
    const client = createLLMClient();
    const resp = await client.complete(messages, { abortSignal: ctrl.signal });
    return { text: resp.text, costInr: resp.costInr, model: resp.model };
  } catch {
    return null;
  } finally {
    clearTimeout(timer);
  }
}

export async function suggestConfig(
  collegeId: string,
  configType: string,
  performedBy: string,
  opts: SuggestConfigOptions = {},
): Promise<SuggestConfigResult> {
  const now = nowOr(opts.now);
  const schema = getRegisteredSchema(configType);
  if (!schema) throw new AppError(404, 'Config type not found');

  // Idempotency check — same (collegeId, configType, performedBy) within window.
  const since = new Date(now.getTime() - IDEMPOTENCY_WINDOW_MS);
  const recent = await ConfigSuggestion.find({
    collegeId,
    configType,
    reviewedBy: { $exists: false },
    generatedAt: { $gte: since },
  })
    .sort({ generatedAt: -1 })
    .lean();

  // A "recent batch" exists if any doc was generated by the same performer within the window.
  // We can't filter by performedBy because suggestions don't carry it; instead we look at
  // batches generated within the window and check the audit log — but for simplicity, a
  // recent batch for this (collegeId, configType) within 30s counts as a duplicate.
  if (recent.length > 0 && recent[0]) {
    const recentBatchId = recent[0].batchId;
    const batchDocs = recent.filter((d) => d.batchId === recentBatchId);
    return {
      batchId: recentBatchId,
      suggestions: batchDocs.map((d) => ({
        field: d.field,
        suggestedValue: d.suggestedValue,
        confidence: d.confidence,
        rationale: d.rationale,
      })),
      llmModel: recent[0].llmModel,
      costInr: batchDocs.reduce((acc, d) => acc + d.costInr, 0),
      generatedAt: recent[0].generatedAt,
      isDuplicate: true,
    };
  }

  // Cap-guard claim.
  const claim = await tryClaimConfigSuggestSlot(collegeId, now);
  if (!claim.allowed) {
    return {
      batchId: '',
      suggestions: [],
      llmModel: '',
      costInr: 0,
      generatedAt: now,
      capReached: true,
      reason: 'daily_limit_exceeded',
    };
  }

  // Build masked context. The PII masker is a defensive layer — none of
  // the v1 collegeProfile fields are PII-bearing, but new additions
  // could be.
  const { masked: maskedContext } = maskPII({
    collegeProfile: opts.collegeProfile ?? {},
    currentValues: opts.currentValues ?? {},
  });

  const messages = buildConfigSuggestPrompt({
    today: now,
    schema,
    maskedContext: maskedContext as {
      collegeProfile: Record<string, unknown>;
      currentValues: Record<string, unknown>;
    },
  });

  const llm = await callLLM(messages);
  if (!llm) {
    return {
      batchId: '',
      suggestions: [],
      llmModel: '',
      costInr: 0,
      generatedAt: now,
      llmFallback: true,
      reason: 'llm_unavailable',
    };
  }

  const parsed = parseConfigSuggestions(llm.text, schema);
  if (parsed.valid.length === 0) {
    return {
      batchId: '',
      suggestions: [],
      llmModel: llm.model,
      costInr: llm.costInr,
      generatedAt: now,
      llmFallback: true,
      reason: parsed.parseError ?? 'no_valid_suggestions',
    };
  }

  // Equal cost division per spec §10.12.
  const batchId = randomUUID();
  const perSuggestionCost = llm.costInr / parsed.valid.length;
  const docs = parsed.valid.map((s) => ({
    collegeId: new mongoose.Types.ObjectId(collegeId),
    configType,
    field: s.field,
    suggestedValue: s.suggestedValue,
    confidence: s.confidence,
    rationale: s.rationale,
    source: 'llm' as const,
    status: 'pending' as const,
    generatedAt: now,
    llmModel: llm.model,
    promptVersion: PROMPT_VERSION,
    costInr: perSuggestionCost,
    batchId,
  }));
  await ConfigSuggestion.insertMany(docs);

  await createAuditLog({
    collegeId,
    entityType: 'ConfigEntry',
    entityId: configType, // there is no doc id at suggest time; configType is the addressable thing
    entityName: schema.label,
    action: 'ai_config_suggested',
    changes: [],
    performedBy,
  });

  return {
    batchId,
    suggestions: parsed.valid.map((s) => ({
      field: s.field,
      suggestedValue: s.suggestedValue,
      confidence: s.confidence,
      rationale: s.rationale,
    })),
    llmModel: llm.model,
    costInr: llm.costInr,
    generatedAt: now,
  };
}

/**
 * Aggregated stats for Story 3 — `GET /config/suggestions/stats`.
 *
 * Note: the aggregation pipeline's FIRST stage MUST filter by collegeId
 * (spec §10.9). Tests in __tests__/service.integration.test.ts pin this.
 */
export type StatsRange = 'today' | 'week' | 'month';

export interface ConfigSuggestStats {
  range: StatsRange;
  totalSuggested: number;
  accepted: number;
  rejected: number;
  pending: number;
  llmCostInr: number;
  byConfigType: Array<{ configType: string; total: number; accepted: number; rejected: number; pending: number; llmCostInr: number }>;
}

export async function getConfigSuggestionStats(
  collegeId: string,
  range: StatsRange = 'today',
  now: Date = new Date(),
): Promise<ConfigSuggestStats> {
  const days = range === 'today' ? 1 : range === 'week' ? 7 : 30;
  const since = new Date(now);
  since.setUTCHours(0, 0, 0, 0);
  since.setUTCDate(since.getUTCDate() - (days - 1));

  const collegeObjectId = new mongoose.Types.ObjectId(collegeId);
  const rows = await ConfigSuggestion.aggregate([
    // §10.9 — collegeId match is the FIRST pipeline stage.
    { $match: { collegeId: collegeObjectId, generatedAt: { $gte: since } } },
    {
      $group: {
        _id: '$configType',
        total: { $sum: 1 },
        accepted: { $sum: { $cond: [{ $eq: ['$status', 'accepted'] }, 1, 0] } },
        rejected: { $sum: { $cond: [{ $eq: ['$status', 'rejected'] }, 1, 0] } },
        pending: { $sum: { $cond: [{ $eq: ['$status', 'pending'] }, 1, 0] } },
        llmCostInr: { $sum: '$costInr' },
      },
    },
    { $sort: { total: -1 } },
  ]);

  const byConfigType = rows.map((r) => ({
    configType: String(r._id),
    total: r.total,
    accepted: r.accepted,
    rejected: r.rejected,
    pending: r.pending,
    llmCostInr: r.llmCostInr,
  }));

  return {
    range,
    totalSuggested: byConfigType.reduce((a, r) => a + r.total, 0),
    accepted: byConfigType.reduce((a, r) => a + r.accepted, 0),
    rejected: byConfigType.reduce((a, r) => a + r.rejected, 0),
    pending: byConfigType.reduce((a, r) => a + r.pending, 0),
    llmCostInr: byConfigType.reduce((a, r) => a + r.llmCostInr, 0),
    byConfigType,
  };
}

/**
 * Called by `upsertConfigEntry` after the config is saved.
 *
 * Marks the listed fields as 'accepted' and the rest of the same batch
 * as 'rejected'. Multi-tenant — only touches docs for the given college.
 */
export async function acceptSuggestionsOnSave(
  collegeId: string,
  batchId: string,
  acceptedFields: string[],
  performedBy: string,
): Promise<void> {
  const collegeObjectId = new mongoose.Types.ObjectId(collegeId);
  const now = new Date();
  await ConfigSuggestion.updateMany(
    { collegeId: collegeObjectId, batchId, field: { $in: acceptedFields }, status: 'pending' },
    { $set: { status: 'accepted', reviewedAt: now, reviewedBy: performedBy } },
  );
  await ConfigSuggestion.updateMany(
    { collegeId: collegeObjectId, batchId, field: { $nin: acceptedFields }, status: 'pending' },
    { $set: { status: 'rejected', reviewedAt: now, reviewedBy: performedBy } },
  );
}
