/**
 * Generates docs/entity-model-reference.md from the actual model files.
 *
 * Usage:
 *   npx ts-node scripts/generate-entity-reference.ts
 *
 * Scans backend/src/models/ for .ts files (excluding index.ts),
 * extracts model names from filenames, and outputs a markdown table
 * grouped by entity group directory.
 *
 * WARNING: This overwrites docs/entity-model-reference.md completely.
 * Hand-edited key field columns will be lost. After running, manually
 * re-add key fields to People, Academic Structure, Root-Level, and
 * Workflow sections (or extend this script to read them from model files).
 */

/* eslint-disable @typescript-eslint/no-var-requires */
const fs = require('fs') as typeof import('fs');
const path = require('path') as typeof import('path');

const MODELS_DIR = path.join(__dirname, '..', 'backend', 'src', 'models');
const OUTPUT_FILE = path.join(__dirname, '..', 'docs', 'entity-model-reference.md');

interface ModelEntry {
  name: string;
  file: string;
}

interface EntityGroup {
  dirName: string;
  displayName: string;
  models: ModelEntry[];
}

const DISPLAY_NAMES: Record<string, string> = {
  'admissions': 'Admissions',
  'people': 'People',
  'academic-structure': 'Academic Structure',
  'academic-ops': 'Academic Ops',
  'finance': 'Finance',
  'hr': 'HR',
  'placement': 'Placement',
  'welfare': 'Welfare',
  'campus': 'Campus',
  'facilities': 'Facilities',
  'library': 'Library',
  'student-dev': 'Student Dev',
  'governance': 'Governance',
  'compliance': 'Compliance',
  'communication': 'Communication',
  'juvi': 'Juvi',
  'workflow': 'Workflow',
};

function scanModels(): { groups: EntityGroup[]; rootModels: ModelEntry[] } {
  const groups: EntityGroup[] = [];
  const rootModels: ModelEntry[] = [];

  const entries = fs.readdirSync(MODELS_DIR, { withFileTypes: true });

  for (const entry of entries) {
    if (entry.isDirectory()) {
      const dirPath = path.join(MODELS_DIR, entry.name);
      const files = fs.readdirSync(dirPath)
        .filter(f => f.endsWith('.ts') && f !== 'index.ts')
        .sort();

      const models = files.map(f => ({
        name: f.replace('.ts', ''),
        file: `models/${entry.name}/${f}`,
      }));

      if (models.length > 0) {
        groups.push({
          dirName: entry.name,
          displayName: DISPLAY_NAMES[entry.name] || entry.name,
          models,
        });
      }
    } else if (entry.isFile() && entry.name.endsWith('.ts') && entry.name !== 'index.ts') {
      rootModels.push({
        name: entry.name.replace('.ts', ''),
        file: `models/${entry.name}`,
      });
    }
  }

  // Sort groups by the order in DISPLAY_NAMES, then alphabetically
  const order = Object.keys(DISPLAY_NAMES);
  groups.sort((a, b) => {
    const ai = order.indexOf(a.dirName);
    const bi = order.indexOf(b.dirName);
    if (ai === -1 && bi === -1) return a.dirName.localeCompare(b.dirName);
    if (ai === -1) return 1;
    if (bi === -1) return -1;
    return ai - bi;
  });

  return { groups, rootModels };
}

function generateMarkdown(groups: EntityGroup[], rootModels: ModelEntry[]): string {
  const totalModels = groups.reduce((sum, g) => sum + g.models.length, 0) + rootModels.length;
  const lines: string[] = [];

  lines.push('# Juvion v2 – Entity Model Reference');
  lines.push('');
  lines.push('> **Status**: DRAFT | Last updated: ' + new Date().toISOString().slice(0, 10));
  lines.push('>');
  lines.push('> Auto-generated by `scripts/generate-entity-reference.ts`.');
  lines.push('> For full field definitions and indexes, see `architecture-spec.md` (Section 3: Entity Groups).');
  lines.push('');
  lines.push(`Total: ${totalModels} models across ${groups.length} entity groups + ${rootModels.length} root-level models`);
  lines.push('');
  lines.push('---');

  for (const group of groups) {
    lines.push('');
    lines.push(`## ${group.displayName} (${group.models.length} models)`);
    lines.push('');
    lines.push('| Model | File |');
    lines.push('|-------|------|');
    for (const model of group.models) {
      lines.push(`| ${model.name} | \`${model.file}\` |`);
    }
  }

  if (rootModels.length > 0) {
    lines.push('');
    lines.push(`## Root-Level Models (${rootModels.length} models)`);
    lines.push('');
    lines.push('| Model | File |');
    lines.push('|-------|------|');
    for (const model of rootModels) {
      lines.push(`| ${model.name} | \`${model.file}\` |`);
    }
  }

  lines.push('');
  return lines.join('\n');
}

function main() {
  const { groups, rootModels } = scanModels();
  const markdown = generateMarkdown(groups, rootModels);

  fs.writeFileSync(OUTPUT_FILE, markdown, 'utf-8');

  const totalModels = groups.reduce((sum, g) => sum + g.models.length, 0) + rootModels.length;
  console.log(`Generated ${OUTPUT_FILE}`);
  console.log(`  ${groups.length} entity groups, ${totalModels} total models`);
  for (const g of groups) {
    console.log(`  - ${g.displayName}: ${g.models.length}`);
  }
  if (rootModels.length > 0) {
    console.log(`  - Root-level: ${rootModels.length}`);
  }
}

main();
